stages:
  transform-format-data:
    cmd: 
    - python -m foreging.pronom > pronom.jsonl
    - python -m foreging.loc_fdd > loc.jsonl
    deps:
    - digipres.github.io/_sources/registries
    outs:
    - loc.jsonl
    - pronom.jsonl
  generate-sqlite:
    cmd:
    - sqlite-utils insert registries.db format --nl loc.jsonl
    - sqlite-utils insert registries.db format --nl pronom.jsonl
    - sqlite-utils enable-fts registries.db format name summary extensions media_types genres
    deps:
    - loc.jsonl
    - pronom.jsonl
    outs:
    - registries.db