[project]
name = "sentinel"
version = "2.0.0"
dependencies = [
 "requests",
 "pyyaml",
 "beautifulsoup4",
 "lxml",
 "rdflib",
 "pydantic",
 "sqlite-utils",
 "sqlmodel"
]

[tool.setuptools.packages.find]
include = ["foreging"]
