on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  update-digipresorg-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install 7-Zip
        run: sudo apt-get install -y p7zip-full p7zip-rar

      - name: Decrypt credentials...
        run: ./decrypt_secrets.sh
        env:
          FFW_PASSWORDFILE_SECRET: ${{ secrets.FFW_PASSWORDFILE_SECRET }}

      - name: Setup Git configuration...
        run: ./setup_git.sh

      - name: Setup Python environment...
        run: ./setup.sh

      - name: Update from various data sources...
        run: ./update.sh

      - name: Deploy updated site...
        run: ./deploy.sh
        env:
          DIGIPRES_REPO_DEPLOY_PRIVATE_KEY: ${{ secrets.DIGIPRES_REPO_DEPLOY_PRIVATE_KEY }}


