on:
  push:
     branches:
       - master

jobs:
  update-digipresorg-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Decrypt credentials...
        run: ./decrypt_secrets.sh
        env:
          FFW_PASSWORDFILE_SECRET: ${{ secrets.FFW_PASSWORDFILE_SECRET }}

      - name: Setup Python environment...
        run: ./setup.sh

      - name: Update from various data sources...
        run: ./update.sh

      - name: Deploy updated site...
        run: ./deploy.sh


